version: '3.3'
services:

    postgres:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres_1
            POSTGRES_USER: postgres
            POSTGRES_DB: youtube_listing
        volumes:
            - ./database:/var/lib/postgresql/data
        ports:
            - 5433:5432
    
    scraper:
        container_name: scraper
        build: 
            dockerfile: Dockerfile
            context: ./scraper
        depends_on:
            - postgres
        # restart: always
        environment: 
            # time interval in sec, after which it will make next api call
            scrape_interval: '30'
            # amount of sec it will wait to retry either connection to db or failed api call
            retry_delay: '10'  
            #  db details
            db_name: youtube_listing
            db_user: postgres
            db_pass: postgres_1
            db_host: postgres
            db_port: "5432"
            # api call variables
            search_keyword: 'new songs'
            # if file name is given single key will be ignored
            api_key_file: keys.txt
            # api_key: AIzaSyCHRnCoEab3KOQnYiUw2dw0iDIzfSAeNrc
            
    api:
        container_name: api
        build: 
            dockerfile: Dockerfile
            context: ./web2py
        restart: always
        depends_on:
            - postgres
            - nginx
        # ports:
        #     - "8081:80"
        volumes:    # mount the application folder to save them localy
            - ./web2py/app/:/home/www-data/web2py/applications/

    nginx:
        container_name: nginx
        build:
            dockerfile: Dockerfile
            context: ./nginx
        restart: always
        external_links:
          - web
        ports: 
          - "8080:80"
          - "4443:443"


volumes:
    api_app:
        driver: local
        driver_opts:
            type: none
            device: $PWD/web2py/app
            o: bind
